events {
    worker_connections 1024;
}

http {
    include       /etc/nginx/mime.types;
    default_type  application/octet-stream;

    server {
        listen 80;

        location / {
            root /webroot/live;
            index index.html;
            try_files $uri $uri/ $uri.html =404;
        }

    }
}
