import type { GlobalConfig } from 'payload'
import { autoTranslateGlobalHook } from '../hooks/translate'

export const Contact: GlobalConfig = {
  slug: 'contact',
  access: {
    read: () => true,
  },
  hooks: {
    afterChange: [autoTranslateGlobalHook],
  },
  fields: [
    {
      name: 'map',
      type: 'group',
      label: 'Headquarters Section Text',
      fields: [
        { name: 'eyebrow', type: 'text', localized: true },
        { name: 'title', type: 'text', localized: true },
        { name: 'subtitle', type: 'textarea', localized: true },
        { name: 'tooltipLabel', type: 'text', localized: true },
        { name: 'tooltipContact', type: 'text', localized: true },
      ],
    },
    {
      name: 'locations',
      type: 'array',
      label: 'Offices / Locations',
      fields: [
        { name: 'name', type: 'text', localized: true, label: 'Office Name' },
        { name: 'address', type: 'text', localized: true, label: 'Address' },
        { name: 'phone', type: 'text', label: 'Phone' },
        { name: 'email', type: 'text', label: 'Email' },
      ],
    },
    {
      name: 'formLabels',
      type: 'group',
      label: 'Contact Form Labels',
      fields: [
        { name: 'eyebrow', type: 'text', localized: true },
        { name: 'title', type: 'text', localized: true },
        { name: 'subtitle', type: 'textarea', localized: true },
        { name: 'addressLabel', type: 'text', localized: true },
        { name: 'infoLabel', type: 'text', localized: true },
        { name: 'mapsLabel', type: 'text', localized: true },
        { name: 'processing', type: 'text', localized: true },
        { name: 'verifying', type: 'text', localized: true },
        { name: 'successTitle', type: 'text', localized: true },
        { name: 'successMessage', type: 'textarea', localized: true },
        { name: 'successSendAnother', type: 'text', localized: true },
        { name: 'error', type: 'text', localized: true },
        { name: 'errorCaptcha', type: 'text', localized: true },
        { name: 'errorRatelimit', type: 'text', localized: true },
        { name: 'errRequired', type: 'text', localized: true },
        { name: 'errEmail', type: 'text', localized: true },
        { name: 'errTooShort', type: 'text', localized: true },
        { name: 'errTooLong', type: 'text', localized: true },
        { name: 'errSubject', type: 'text', localized: true },
        { name: 'nameLabel', type: 'text', localized: true },
        { name: 'namePlaceholder', type: 'text', localized: true },
        { name: 'companyLabel', type: 'text', localized: true },
        { name: 'companyPlaceholder', type: 'text', localized: true },
        { name: 'emailLabel', type: 'text', localized: true },
        { name: 'emailPlaceholder', type: 'text', localized: true },
        { name: 'subjectLabel', type: 'text', localized: true },
        { name: 'subjectPlaceholder', type: 'text', localized: true },
        { name: 'subjectProducts', type: 'text', localized: true },
        { name: 'subjectPartner', type: 'text', localized: true },
        { name: 'subjectQuality', type: 'text', localized: true },
        { name: 'subjectOther', type: 'text', localized: true },
        { name: 'messageLabel', type: 'text', localized: true },
        { name: 'messagePlaceholder', type: 'text', localized: true },
        { name: 'submitLabel', type: 'text', localized: true },
      ],
    },
  ],
}
