/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    users: User;
    media: Media;
    'project-categories': ProjectCategory;
    projects: Project;
    certificates: Certificate;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    'project-categories': ProjectCategoriesSelect<false> | ProjectCategoriesSelect<true>;
    projects: ProjectsSelect<false> | ProjectsSelect<true>;
    certificates: CertificatesSelect<false> | CertificatesSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: string;
  };
  fallbackLocale:
    | ('false' | 'none' | 'null')
    | false
    | null
    | ('es' | 'en' | 'de' | 'pl')
    | ('es' | 'en' | 'de' | 'pl')[];
  globals: {
    header: Header;
    hero: Hero;
    mission: Mission;
    vision: Vision;
    innovation: Innovation;
    'products-section': ProductsSection;
    quote: Quote;
    clients: Client;
    contact: Contact;
    awards: Award;
    'certifications-content': CertificationsContent;
    'rd-content': RdContent;
    'history-content': HistoryContent;
    careers: Career;
    faq: Faq;
    seo: Seo;
  };
  globalsSelect: {
    header: HeaderSelect<false> | HeaderSelect<true>;
    hero: HeroSelect<false> | HeroSelect<true>;
    mission: MissionSelect<false> | MissionSelect<true>;
    vision: VisionSelect<false> | VisionSelect<true>;
    innovation: InnovationSelect<false> | InnovationSelect<true>;
    'products-section': ProductsSectionSelect<false> | ProductsSectionSelect<true>;
    quote: QuoteSelect<false> | QuoteSelect<true>;
    clients: ClientsSelect<false> | ClientsSelect<true>;
    contact: ContactSelect<false> | ContactSelect<true>;
    awards: AwardsSelect<false> | AwardsSelect<true>;
    'certifications-content': CertificationsContentSelect<false> | CertificationsContentSelect<true>;
    'rd-content': RdContentSelect<false> | RdContentSelect<true>;
    'history-content': HistoryContentSelect<false> | HistoryContentSelect<true>;
    careers: CareersSelect<false> | CareersSelect<true>;
    faq: FaqSelect<false> | FaqSelect<true>;
    seo: SeoSelect<false> | SeoSelect<true>;
  };
  locale: 'es' | 'en' | 'de' | 'pl';
  widgets: {
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: string;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: string;
  alt: string;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "project-categories".
 */
export interface ProjectCategory {
  id: string;
  name: string;
  description?: string | null;
  logo: string | Media;
  identifier: string;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "projects".
 */
export interface Project {
  id: string;
  category: string | ProjectCategory;
  title: string;
  client: string;
  description: string;
  file?: (string | null) | Media;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "certificates".
 */
export interface Certificate {
  id: string;
  type: 'Calidad' | 'Medio Ambiente';
  name: string;
  issuer: string;
  issueDate?: string | null;
  file?: (string | null) | Media;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: string;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: string;
  document?:
    | ({
        relationTo: 'users';
        value: string | User;
      } | null)
    | ({
        relationTo: 'media';
        value: string | Media;
      } | null)
    | ({
        relationTo: 'project-categories';
        value: string | ProjectCategory;
      } | null)
    | ({
        relationTo: 'projects';
        value: string | Project;
      } | null)
    | ({
        relationTo: 'certificates';
        value: string | Certificate;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: string | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: string;
  user: {
    relationTo: 'users';
    value: string | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: string;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "project-categories_select".
 */
export interface ProjectCategoriesSelect<T extends boolean = true> {
  name?: T;
  description?: T;
  logo?: T;
  identifier?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "projects_select".
 */
export interface ProjectsSelect<T extends boolean = true> {
  category?: T;
  title?: T;
  client?: T;
  description?: T;
  file?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "certificates_select".
 */
export interface CertificatesSelect<T extends boolean = true> {
  type?: T;
  name?: T;
  issuer?: T;
  issueDate?: T;
  file?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "header".
 */
export interface Header {
  id: string;
  header?: {
    company?: string | null;
    products?: string | null;
    clients?: string | null;
    contact?: string | null;
    contactCta?: string | null;
  };
  footerColumns?: {
    company?: string | null;
    products?: string | null;
    contact?: string | null;
  };
  links?: {
    mission?: string | null;
    vision?: string | null;
    innovation?: string | null;
    history?: string | null;
    awards?: string | null;
    certifications?: string | null;
    rd?: string | null;
    presence?: string | null;
    careers?: string | null;
    clients?: string | null;
    contact?: string | null;
    dashboard?: string | null;
    door?: string | null;
    functional?: string | null;
    exterior?: string | null;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "hero".
 */
export interface Hero {
  id: string;
  eyebrow?: string | null;
  titleLine1?: string | null;
  titleLine2?: string | null;
  subtitle?: string | null;
  ctas?: {
    primary?: string | null;
    secondary?: string | null;
  };
  scrollText?: string | null;
  stats?:
    | {
        value?: string | null;
        label?: string | null;
        id?: string | null;
      }[]
    | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "mission".
 */
export interface Mission {
  id: string;
  eyebrow?: string | null;
  title?: string | null;
  body1?: string | null;
  body2?: string | null;
  cta?: string | null;
  badgeLabel?: string | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "vision".
 */
export interface Vision {
  id: string;
  eyebrow?: string | null;
  title?: string | null;
  body?: string | null;
  cta?: string | null;
  values?:
    | {
        title?: string | null;
        text?: string | null;
        id?: string | null;
      }[]
    | null;
  gallery?:
    | {
        image: string | Media;
        alt?: string | null;
        id?: string | null;
      }[]
    | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "innovation".
 */
export interface Innovation {
  id: string;
  eyebrow?: string | null;
  title?: string | null;
  subtitle?: string | null;
  features?:
    | {
        title?: string | null;
        text?: string | null;
        id?: string | null;
      }[]
    | null;
  stat1Value?: string | null;
  stat1Label?: string | null;
  stat2Value?: string | null;
  stat2Label?: string | null;
  loadingText?: string | null;
  rotateText?: string | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "products-section".
 */
export interface ProductsSection {
  id: string;
  sectionHeader?: {
    eyebrow?: string | null;
    title?: string | null;
    subtitle?: string | null;
    cta?: string | null;
  };
  products?:
    | {
        title: string;
        description?: string | null;
        category?: string | null;
        image?: (string | null) | Media;
        features?:
          | {
              feature?: string | null;
              id?: string | null;
            }[]
          | null;
        id?: string | null;
      }[]
    | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "quote".
 */
export interface Quote {
  id: string;
  text: string;
  philosophy?: string | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "clients".
 */
export interface Client {
  id: string;
  eyebrow?: string | null;
  title?: string | null;
  subtitle?: string | null;
  logos?:
    | {
        image: string | Media;
        name?: string | null;
        id?: string | null;
      }[]
    | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "contact".
 */
export interface Contact {
  id: string;
  map?: {
    eyebrow?: string | null;
    title?: string | null;
    subtitle?: string | null;
    tooltipLabel?: string | null;
    tooltipContact?: string | null;
  };
  locations?:
    | {
        name?: string | null;
        address?: string | null;
        phone?: string | null;
        email?: string | null;
        id?: string | null;
      }[]
    | null;
  formLabels?: {
    eyebrow?: string | null;
    title?: string | null;
    subtitle?: string | null;
    addressLabel?: string | null;
    infoLabel?: string | null;
    mapsLabel?: string | null;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "awards".
 */
export interface Award {
  id: string;
  title?: string | null;
  subtitle?: string | null;
  list?:
    | {
        award?: string | null;
        id?: string | null;
      }[]
    | null;
  meta?: {
    title?: string | null;
    description?: string | null;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "certifications-content".
 */
export interface CertificationsContent {
  id: string;
  eyebrow?: string | null;
  title?: string | null;
  subtitle?: string | null;
  qualityCommitment?: {
    title?: string | null;
    body?: string | null;
  };
  stats?: {
    auditLabel?: string | null;
    auditValue?: string | null;
    defectLabel?: string | null;
    defectValue?: string | null;
    traceabilityLabel?: string | null;
    traceabilityValue?: string | null;
  };
  meta?: {
    title?: string | null;
    description?: string | null;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "rd-content".
 */
export interface RdContent {
  id: string;
  eyebrow?: string | null;
  title?: string | null;
  subtitle?: string | null;
  stats?:
    | {
        value?: string | null;
        label?: string | null;
        id?: string | null;
      }[]
    | null;
  funders?: {
    label?: string | null;
    programLabel?: string | null;
    items?:
      | {
          name?: string | null;
          description?: string | null;
          id?: string | null;
        }[]
      | null;
  };
  contact?: {
    title?: string | null;
    body?: string | null;
    cta?: string | null;
  };
  meta?: {
    title?: string | null;
    description?: string | null;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "history-content".
 */
export interface HistoryContent {
  id: string;
  eyebrow?: string | null;
  title?: string | null;
  pageTitle?: string | null;
  pageSubtitle?: string | null;
  timeline?:
    | {
        year?: string | null;
        text?: string | null;
        id?: string | null;
      }[]
    | null;
  todayText?: string | null;
  todayLabel?: string | null;
  meta?: {
    title?: string | null;
    description?: string | null;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "careers".
 */
export interface Career {
  id: string;
  title?: string | null;
  subtitle?: string | null;
  email?: string | null;
  emailLabel?: string | null;
  phone?: string | null;
  phoneLabel?: string | null;
  phoneHours?: string | null;
  cvHint?: string | null;
  linkedinCta?: string | null;
  linkedinShort?: string | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "faq".
 */
export interface Faq {
  id: string;
  eyebrow?: string | null;
  title?: string | null;
  questions?:
    | {
        question?: string | null;
        answer?: string | null;
        id?: string | null;
      }[]
    | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "seo".
 */
export interface Seo {
  id: string;
  default?: {
    title?: string | null;
    description?: string | null;
  };
  notFound?: {
    title?: string | null;
    subtitle?: string | null;
    cta?: string | null;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "header_select".
 */
export interface HeaderSelect<T extends boolean = true> {
  header?:
    | T
    | {
        company?: T;
        products?: T;
        clients?: T;
        contact?: T;
        contactCta?: T;
      };
  footerColumns?:
    | T
    | {
        company?: T;
        products?: T;
        contact?: T;
      };
  links?:
    | T
    | {
        mission?: T;
        vision?: T;
        innovation?: T;
        history?: T;
        awards?: T;
        certifications?: T;
        rd?: T;
        presence?: T;
        careers?: T;
        clients?: T;
        contact?: T;
        dashboard?: T;
        door?: T;
        functional?: T;
        exterior?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "hero_select".
 */
export interface HeroSelect<T extends boolean = true> {
  eyebrow?: T;
  titleLine1?: T;
  titleLine2?: T;
  subtitle?: T;
  ctas?:
    | T
    | {
        primary?: T;
        secondary?: T;
      };
  scrollText?: T;
  stats?:
    | T
    | {
        value?: T;
        label?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "mission_select".
 */
export interface MissionSelect<T extends boolean = true> {
  eyebrow?: T;
  title?: T;
  body1?: T;
  body2?: T;
  cta?: T;
  badgeLabel?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "vision_select".
 */
export interface VisionSelect<T extends boolean = true> {
  eyebrow?: T;
  title?: T;
  body?: T;
  cta?: T;
  values?:
    | T
    | {
        title?: T;
        text?: T;
        id?: T;
      };
  gallery?:
    | T
    | {
        image?: T;
        alt?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "innovation_select".
 */
export interface InnovationSelect<T extends boolean = true> {
  eyebrow?: T;
  title?: T;
  subtitle?: T;
  features?:
    | T
    | {
        title?: T;
        text?: T;
        id?: T;
      };
  stat1Value?: T;
  stat1Label?: T;
  stat2Value?: T;
  stat2Label?: T;
  loadingText?: T;
  rotateText?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "products-section_select".
 */
export interface ProductsSectionSelect<T extends boolean = true> {
  sectionHeader?:
    | T
    | {
        eyebrow?: T;
        title?: T;
        subtitle?: T;
        cta?: T;
      };
  products?:
    | T
    | {
        title?: T;
        description?: T;
        category?: T;
        image?: T;
        features?:
          | T
          | {
              feature?: T;
              id?: T;
            };
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "quote_select".
 */
export interface QuoteSelect<T extends boolean = true> {
  text?: T;
  philosophy?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "clients_select".
 */
export interface ClientsSelect<T extends boolean = true> {
  eyebrow?: T;
  title?: T;
  subtitle?: T;
  logos?:
    | T
    | {
        image?: T;
        name?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "contact_select".
 */
export interface ContactSelect<T extends boolean = true> {
  map?:
    | T
    | {
        eyebrow?: T;
        title?: T;
        subtitle?: T;
        tooltipLabel?: T;
        tooltipContact?: T;
      };
  locations?:
    | T
    | {
        name?: T;
        address?: T;
        phone?: T;
        email?: T;
        id?: T;
      };
  formLabels?:
    | T
    | {
        eyebrow?: T;
        title?: T;
        subtitle?: T;
        addressLabel?: T;
        infoLabel?: T;
        mapsLabel?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "awards_select".
 */
export interface AwardsSelect<T extends boolean = true> {
  title?: T;
  subtitle?: T;
  list?:
    | T
    | {
        award?: T;
        id?: T;
      };
  meta?:
    | T
    | {
        title?: T;
        description?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "certifications-content_select".
 */
export interface CertificationsContentSelect<T extends boolean = true> {
  eyebrow?: T;
  title?: T;
  subtitle?: T;
  qualityCommitment?:
    | T
    | {
        title?: T;
        body?: T;
      };
  stats?:
    | T
    | {
        auditLabel?: T;
        auditValue?: T;
        defectLabel?: T;
        defectValue?: T;
        traceabilityLabel?: T;
        traceabilityValue?: T;
      };
  meta?:
    | T
    | {
        title?: T;
        description?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "rd-content_select".
 */
export interface RdContentSelect<T extends boolean = true> {
  eyebrow?: T;
  title?: T;
  subtitle?: T;
  stats?:
    | T
    | {
        value?: T;
        label?: T;
        id?: T;
      };
  funders?:
    | T
    | {
        label?: T;
        programLabel?: T;
        items?:
          | T
          | {
              name?: T;
              description?: T;
              id?: T;
            };
      };
  contact?:
    | T
    | {
        title?: T;
        body?: T;
        cta?: T;
      };
  meta?:
    | T
    | {
        title?: T;
        description?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "history-content_select".
 */
export interface HistoryContentSelect<T extends boolean = true> {
  eyebrow?: T;
  title?: T;
  pageTitle?: T;
  pageSubtitle?: T;
  timeline?:
    | T
    | {
        year?: T;
        text?: T;
        id?: T;
      };
  todayText?: T;
  todayLabel?: T;
  meta?:
    | T
    | {
        title?: T;
        description?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "careers_select".
 */
export interface CareersSelect<T extends boolean = true> {
  title?: T;
  subtitle?: T;
  email?: T;
  emailLabel?: T;
  phone?: T;
  phoneLabel?: T;
  phoneHours?: T;
  cvHint?: T;
  linkedinCta?: T;
  linkedinShort?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "faq_select".
 */
export interface FaqSelect<T extends boolean = true> {
  eyebrow?: T;
  title?: T;
  questions?:
    | T
    | {
        question?: T;
        answer?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "seo_select".
 */
export interface SeoSelect<T extends boolean = true> {
  default?:
    | T
    | {
        title?: T;
        description?: T;
      };
  notFound?:
    | T
    | {
        title?: T;
        subtitle?: T;
        cta?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}